"""add mediations participants

Revision ID: 57cab6f24746
Revises: 6dff7c968424
Create Date: 2026-04-30 04:10:54.749474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57cab6f24746'
down_revision: Union[str, Sequence[str], None] = '6dff7c968424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediations_id'), 'mediations', ['id'], unique=False)
    op.create_table('mediation_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mediation_id'], ['mediations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediation_participants_id'), 'mediation_participants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mediation_participants_id'), table_name='mediation_participants')
    op.drop_table('mediation_participants')
    op.drop_index(op.f('ix_mediations_id'), table_name='mediations')
    op.drop_table('mediations')
    # ### end Alembic commands ###
