"""init clean

Revision ID: 6dff7c968424
Revises: 
Create Date: 2026-04-30 03:57:34.003194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dff7c968424'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediation_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediation_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invited_email', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediation_invites_id'), 'mediation_invites', ['id'], unique=False)
    op.create_index(op.f('ix_mediation_invites_mediation_id'), 'mediation_invites', ['mediation_id'], unique=False)
    op.create_index(op.f('ix_mediation_invites_token_hash'), 'mediation_invites', ['token_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mediation_invites_token_hash'), table_name='mediation_invites')
    op.drop_index(op.f('ix_mediation_invites_mediation_id'), table_name='mediation_invites')
    op.drop_index(op.f('ix_mediation_invites_id'), table_name='mediation_invites')
    op.drop_table('mediation_invites')
    # ### end Alembic commands ###
