"""add mediation fields

Revision ID: c5186840d064
Revises: 57cab6f24746
Create Date: 2026-05-02 19:31:41.455490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5186840d064'
down_revision: Union[str, Sequence[str], None] = '57cab6f24746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediations', sa.Column('mediation_type', sa.String(), nullable=False))
    op.add_column('mediations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('mediations', sa.Column('priority', sa.Text(), nullable=True))
    op.add_column('mediations', sa.Column('role', sa.String(), nullable=True))
    op.add_column('mediations', sa.Column('status', sa.String(), nullable=True))
  
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('mediations', 'status')
    op.drop_column('mediations', 'role')
    op.drop_column('mediations', 'priority')
    op.drop_column('mediations', 'description')
    op.drop_column('mediations', 'mediation_type')
    # ### end Alembic commands ###
